### ISSUE TITLE
Add a Spark example

### ISSUE THREAD

**Issue by sbrunk** [almond-sh/examples#1]
It would be great to have a Spark example based on https://github.com/alexarchambault/ammonite-spark.

- [x] Create the example notebook
- [x] ~~Investigate how to run a minimal standalone Spark cluster in binder~~ running in local mode works

**Comment by sbrunk** [comment]
We should use the next release that contains almond-sh/almond#310 with Scala 2.12 support.

**Comment by alexarchambault** [comment]
I opened https://github.com/almond-sh/almond/pull/310 while trying stuff for that issue.

**Comment by alexarchambault** [comment]
[This notebook](https://gist.github.com/alexarchambault/fb4dd954d29232e8406d091fbb825a78) is basically how I use it. (The "100 / 100" stuff correspond to progress bars, that seem not to render well on GitHub.) (edit: deleted the first version of the gist, that contained personnal IP addresses…)

**Comment by sbrunk** [comment]
Great! Lets use that for a start.

BTW nbviewer can also render gists: https://nbviewer.jupyter.org/gist/alexarchambault/fb4dd954d29232e8406d091fbb825a78

**Comment by alexarchambault** [comment]
Just so you know, there was some discussions about trying to have  @krishnan-r's https://github.com/krishnan-r/sparkmonitor work in almond. That would be a better alternative to the current progress bars.

**Comment by sbrunk** [comment]
I've just added the notebook. It's basically yours & a bit of explanations. Feel free to enhance. :)

Right now it depends on 0.2.3-SNAPSHOT so it only works if you publish and install the kernel locally. Once you've published the next release, I'll update it and merge into master.

**Comment by sbrunk** [comment]
I'd also like to add a cell that shows how a `DataFrame` can be displayed as a HTML table.
I haven't really found something to does this out of the box already. Even with PySpark people seem to just convert to a Pandas DataFrame which supports table display.

We could do something like @Aivean has posted in almond-sh/almond#180 for now. Perhaps even add that to the *almond-spark* module.
