### ISSUE TITLE
Consider adding ReviewNB for better notebook diffs

### ISSUE THREAD

**Issue by sbrunk** [almond-sh/examples#10]
[ReviewNB](https://www.reviewnb.com/) is a GitHub app that gives you nice notebook diffs like [nbdime](https://nbdime.readthedocs.io/en/latest/) but integrated in PRs and with review support.

Because we're dealing mostly with notebooks in this repo I think adding it might helpful.

**Comment by alexarchambault** [comment]
Done for both the [main repo](https://app.reviewnb.com/almond-sh/almond/pulls/) and the [examples](https://app.reviewnb.com/almond-sh/examples/pulls/).

**Comment by sbrunk** [comment]
Great, thanks! :)
